# 데이터프레임(DataFrame)

In [3]:
import pandas as pd # pandas에서 Series와 DataFrame 사용가능

In [4]:
# 데이터프레임 생성(index 없이)
df = pd.DataFrame({'KOSPI': [1915, 1961, 2026, 2467, 2041], 'KOSDAQ': [542, 682, 631, 798, 675]})
df

   KOSPI  KOSDAQ
0   1915     542
1   1961     682
2   2026     631
3   2467     798
4   2041     675

In [5]:
# 데이터프레임 생성(index 없이)
df = pd.DataFrame({'KOSPI': [1915, 1961, 2026, 2467, 2041], 'KOSDAQ': [542, 682, 631, 798, 675]}, index = [2014, 2015, 2016, 2017, 2018])
df

      KOSPI  KOSDAQ
2014   1915     542
2015   1961     682
2016   2026     631
2017   2467     798
2018   2041     675

In [6]:
df.describe() # 원소의 갯수, 평균, 표준편차, 최솟값, 제1&2&3 사분위수, 최댓값

             KOSPI      KOSDAQ
count     5.000000    5.000000
mean   2082.000000  665.600000
std     221.117616   92.683871
min    1915.000000  542.000000
25%    1961.000000  631.000000
50%    2026.000000  675.000000
75%    2041.000000  682.000000
max    2467.000000  798.000000

In [7]:
df.info() # 인덱스 정보, 전체 칼럼 정보, 1 & 2번째 칼럼 정보, 자료형, 메모리 사용량

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 2014 to 2018
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   KOSPI   5 non-null      int64
 1   KOSDAQ  5 non-null      int64
dtypes: int64(2)
memory usage: 120.0 bytes

In [12]:
# 시리즈를 데이터프레임으로 생성
kospi = pd.Series([1915, 1961, 2026, 2467, 2041],index = [2014, 2015, 2016, 2017, 2018] , name = 'KOSPI')
kosdaq = pd.Series([542, 682, 631, 798, 675], index = [2014, 2015, 2016, 2017, 2018], name = 'KOSDAQ')

df = pd.DataFrame({kospi.name : kospi, kosdaq.name : kosdaq})
df

      KOSPI  KOSDAQ
2014   1915     542
2015   1961     682
2016   2026     631
2017   2467     798
2018   2041     675

In [13]:
# 순회처리 1
for i in df.index:
  print(i, df['KOSPI'][i], df['KOSDAQ'][i])

2014 1915 542
2015 1961 682
2016 2026 631
2017 2467 798
2018 2041 675

In [15]:
# 순회처리 2: itertuples() 는 각 행을 튜플 형태로 반환함
for row in df.itertuples(name = 'KRX'):
  print(row)

KRX(Index=2014, KOSPI=1915, KOSDAQ=542)
KRX(Index=2015, KOSPI=1961, KOSDAQ=682)
KRX(Index=2016, KOSPI=2026, KOSDAQ=631)
KRX(Index=2017, KOSPI=2467, KOSDAQ=798)
KRX(Index=2018, KOSPI=2041, KOSDAQ=675)

In [17]:
for row in df.itertuples():
  print(row[0], row[1], row[2])

2014 1915 542
2015 1961 682
2016 2026 631
2017 2467 798
2018 2041 675